# RNN Data

In [220]:
import torch 
from torch import nn
# 3D music in L N Hin
# X = torch.tensor([[[1,2],[3,4],[5,6]],
#                      [[5,6],[7,8],[9,10]],
#                      [[11,12],[13,14],[15,16]],
#                      [[17,18],[19,20],[21,22]]],dtype=torch.float32)
# L,N,Hin = X.shape\
# h0 = torch.zeros(1, N, Hout)
# 2D Music L Hin
X = torch.tensor([[1,2],
                     [3,4],
                     [5,6],
                     [7,8]],dtype=torch.float32)
L,Hin = X.shape
# Hout you pick, output number for every music (hidden size)
# Hin number of music in your music, music channels (defalt) (input size)




# Hyperparametmers

In [221]:
Hout = 1 # Size of the hidden state
h0 = torch.zeros(1, Hout)

wx = torch.tensor([[0.05,0.2]],dtype=torch.float32) # Shape of (hidden_size,input size)
bx = torch.tensor([0.2],dtype=torch.float32) # Shape of (hidden_size)

wh = torch.tensor([[0.1]],dtype=torch.float32)#shape of (hidden_size, hidden_size)
bh = torch.tensor([0.3],dtype=torch.float32)#Shape of (hidden_size)



# RNN Ref

In [222]:

#Hin = 2 # Number of Channels

# L,Hin = input.shape
Rnn = nn.RNN(input_size=Hin,hidden_size=Hout)
Rnn.weight_ih_l0.data = wx
Rnn.bias_ih_l0.data = bx

Rnn.weight_hh_l0.data = wh
Rnn.bias_hh_l0.data = bh
output, hn = Rnn(input, h0)
# Output (L,N,D * Hout)
print(f"output {output}\n, hn {hn}")

# dir(rnn)


output tensor([[0.7398],
        [0.9094],
        [0.9668],
        [0.9878]], grad_fn=<SqueezeBackward1>)
, hn tensor([[0.9878]], grad_fn=<SqueezeBackward1>)


# DIY LOOP

In [236]:
ht_1 = h0 # ht - 1
for t in range(L):
    x = X[t]
    wxTx = torch.dot(wx.flatten(),x)
    whTh = torch.dot(wh.flatten(),ht_1.flatten())
    ht = torch.tanh(wxTx+bx+whTh+bh)
    ht_1 = ht
    print(ht)
    
# print(output)
# Rnn(X,1)


tensor([0.7398])
tensor([0.9094])
tensor([0.9668])
tensor([0.9878])


### DIY RNNCell

In [224]:

# X = torch.tensor([[1,2],[3,4],[5,6]],dtype=torch.float32)/50
# h = torch.tensor([[0.1],[0.2],[0.3]],dtype=torch.float32)

#ih
f = nn.Linear(in_features=2,out_features=1)
f.weight.data = torch.tensor([[7,8]],dtype=torch.float32)/50
f.bias.data = torch.tensor([0.2],dtype=torch.float32)

#hh
F = nn.Linear(in_features=2,out_features=1)
F.weight.data = torch.tensor([[0.1]],dtype=torch.float32)
F.bias.data = torch.tensor([0.3],dtype=torch.float32)

#tanh
# sig = torch.tanh(f(X)+F(h))
# print(sig)

### RNNCell No loop

In [238]:

#ih
rnnCell = nn.RNNCell(input_size=Hin, hidden_size=Hout)  
rnnCell.weight_ih.data = wx
rnnCell.bias_ih.data = bx
rnnCell.bias_hh.data = bh
rnnCell.weight_hh.data = wh
#hh
ht_1 = h0
for t in range(L):
    ht = rnnCell(X[t],ht_1)
    ht_1 = ht
    print(ht)
    


tensor([[0.7398]], grad_fn=<SqueezeBackward1>)
tensor([[0.9094]], grad_fn=<SqueezeBackward1>)
tensor([[0.9668]], grad_fn=<SqueezeBackward1>)
tensor([[0.9878]], grad_fn=<SqueezeBackward1>)


Hw:
make weight non-random
'weight_hh_l0',
'bias_hh_l0',

'weight_ih_l0',
 bias_ih_l0',

 tanh(weight * input + weight * h)
 

 RNNCell does if for only one L
 RNN doews it for all L

 Goal:
  manual + Loop code(L)= RNNCell + loop code(L) = RNN code


### DIY RNN

In [ ]:
# 3 Different ways to do the Dot Product
a = torch.tensor([[1],[2]])
b = torch.tensor([[3],[4]])

#1
(a*b).sum()

#2
a.T @ b

#3
torch.dot(a.flatten(),b.flatten())


tensor(11)

In [ ]:
w = Rnn.weight_ih_l0.data
x = X[0]
torch.dot(w.flatten(),x)

w.T.flatten() @ x

sum(w.flatten()*x)

tensor(0.4600)

# Hw

1. use torch.allclose to compare RNN RNNCell DIY
2. Try Hidden_size = 2 
3. Clean up code 