In [23]:
import torch 
from torch import nn
                #CH1 CH2
X = torch.tensor([[1,2], #Music Sample 1
                     [3,4], #Music Sample 2
                     [5,6], #Music Sample 2
                     [7,8]],dtype=torch.float32)/500#Music Sample 5
L,Hin = X.shape



In [24]:
Hout = 5 # Size of the hidden state
h0 = torch.zeros(1, Hout)

Wx = torch.rand(Hout,Hin) # Shape of (hidden_size(Hout),input size(Hin))
bx = torch.rand(Hout) # Shape of (hidden_size)

Wh = torch.rand(Hout,Hout)#shape of (hidden_size, hidden_size)
bh = torch.rand(Hout)#Shape of (hidden_size)



In [25]:
Rnn = nn.RNN(input_size=Hin,hidden_size=Hout)
Rnn.weight_ih_l0.data = Wx
Rnn.bias_ih_l0.data = bx
Rnn.weight_hh_l0.data = Wh
Rnn.bias_hh_l0.data = bh
output, hn = Rnn(X, h0)
print(f"output {output}\n, hn {hn}")


output tensor([[0.5693, 0.3791, 0.6364, 0.6342, 0.9096],
        [0.9809, 0.9904, 0.9816, 0.9868, 0.9930],
        [0.9984, 0.9993, 0.9967, 0.9984, 0.9986],
        [0.9986, 0.9994, 0.9970, 0.9985, 0.9986]], grad_fn=<SqueezeBackward1>)
, hn tensor([[0.9986, 0.9994, 0.9970, 0.9985, 0.9986]], grad_fn=<SqueezeBackward1>)


In [ ]:
ht_1 = h0 # ht - 1
for t in range(L):
    x = X[t]
    wxTx = torch.matmul(x,Wx.T)
    whTh = torch.matmul(ht_1, Wh.T)
    ht = torch.tanh(wxTx+bx+whTh+bh)
    ht_1 = ht
    print(ht)
    
torch.allclose(hn,ht)
# print(output)
# Rnn(X,1)


tensor([[0.5693, 0.3791, 0.6364, 0.6342, 0.9096]])
tensor([[0.9809, 0.9904, 0.9816, 0.9868, 0.9930]])
tensor([[0.9984, 0.9993, 0.9967, 0.9984, 0.9986]])
tensor([[0.9986, 0.9994, 0.9970, 0.9985, 0.9986]])


True

HW.

Finish the RNN Cell
N = multiable number
